#!/usr/bin/env python3
"""gap-report.py — regenerate sources/gap-report.md (mechanical).

Aggregates, grouped by folder then note:
  - every `⚠ Flagged gap — no corpus source` line (with its section),
  - every `⚠ Flagged stub — no corpus source yet` router row,
  - every `unknown` infobox value on a `layout: v2` note.

This IS the "what knowledge are we missing" deliverable the structure pass
exists to produce: Cameron reads it to decide what sources to go find.
Invoked by the workflow checkpoint step (never by link-maintenance — the
idempotence contract stays untouched). Whole file regenerated between
markers; prose outside them is preserved.
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent.parent
sys.path.insert(0, str(ROOT / "scripts"))
import note_schema  # noqa: E402

OUT = ROOT / "sources" / "gap-report.md"
START, END = "<!-- review:gaps:start -->", "<!-- review:gaps:end -->"
FOLDERS = ["species", "techniques", "lures", "rigging", "conditions",
           "seasonal", "bait", "locations", "planning", "fish-care", "tackle"]

DEFAULT = """# Gap report

The KB's known knowledge gaps, generated by scripts/review/gap-report.py from
the flagged-gap lines, flagged stubs, and `unknown` infobox values across the
tree. Corpus-only rule (sources/plan-review.md): a gap is filled by finding a
source, never by invention.

<!-- review:gaps:start -->
<!-- review:gaps:end -->
"""


def main() -> int:
    entries: dict[str, list[str]] = {}
    totals = {"gap": 0, "stub": 0, "unknown": 0}
    for folder in FOLDERS:
        for path in sorted((ROOT / folder).rglob("*.md")):
            if path.name == "README.md" or path.parent.name == "evidence":
                continue
            rel = str(path.relative_to(ROOT))
            text = path.read_text(encoding="utf-8")
            section = "(lead)"
            notes: list[str] = []
            for line in text.splitlines():
                if line.startswith("## "):
                    section = line[3:].strip()
                if note_schema.FLAG_GAP in line:
                    detail = line.split(note_schema.FLAG_GAP, 1)[1].strip(" :—-")
                    notes.append(f"  - `{section}`: gap"
                                 + (f" — {detail}" if detail else ""))
                    totals["gap"] += 1
                elif note_schema.FLAG_STUB in line:
                    notes.append(f"  - `{section}`: flagged stub row")
                    totals["stub"] += 1
            if note_schema.layout_of(text) == note_schema.LAYOUT_CURRENT:
                ntype = note_schema.fm_value(text, "type")
                for key in note_schema.INFOBOX_FIELDS.get(ntype, []):
                    if note_schema.fm_value(text, key) == "unknown":
                        notes.append(f"  - infobox `{key}`: unknown")
                        totals["unknown"] += 1
            if notes:
                entries.setdefault(folder, []).append(
                    f"- **{rel}**\n" + "\n".join(notes))

    lines = [f"_Totals: {totals['gap']} flagged gaps, {totals['stub']} "
             f"flagged stubs, {totals['unknown']} unknown infobox values._", ""]
    for folder in FOLDERS:
        if folder in entries:
            lines.append(f"## {folder}/")
            lines.append("")
            lines.extend(entries[folder])
            lines.append("")

    text = OUT.read_text(encoding="utf-8") if OUT.exists() else DEFAULT
    if START not in text:
        text = DEFAULT
    pre, rest = text.split(START, 1)
    _mid, post = rest.split(END, 1)
    OUT.write_text(pre + START + "\n" + "\n".join(lines).rstrip() + "\n" + END
                   + post, encoding="utf-8")
    print(f"gap-report: {totals['gap']} gaps, {totals['stub']} stubs, "
          f"{totals['unknown']} unknowns across "
          f"{sum(len(v) for v in entries.values())} notes")
    return 0


if __name__ == "__main__":
    sys.exit(main())
